/**
 * File generated by npx create-expo-app
 */

import type { PropsWithChildren } from 'react';
import { StyleSheet } from 'react-native';

import { ThemedView } from '@/components/ThemedView';
import { ScrollView } from 'react-native-gesture-handler';

const ParallaxScrollView: React.FC<PropsWithChildren> = ({ children }) => (
  <ThemedView style={styles.container}>
    <ScrollView contentContainerStyle={styles.scrollView}>
      <ThemedView style={styles.content}>{children}</ThemedView>
    </ScrollView>
  </ThemedView>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flexGrow: 1,
  },
  content: {
    flex: 1,
    paddingTop: 40,
    paddingHorizontal: 24,
  },
});

export default ParallaxScrollView;
