/**
 * File generated by npx create-expo-app
 */

import type { PropsWithChildren } from "react";
import { StyleSheet } from "react-native";

import { ThemedView } from "@/components/ThemedView";
import { ScrollView } from "react-native-gesture-handler";
import { SafeAreaView } from "react-native-safe-area-context";

const ParallaxScrollView: React.FC<PropsWithChildren> = ({ children }) => (
  <SafeAreaView style={styles.safeArea}>
    <ThemedView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollView}>
        <ThemedView style={styles.content}>{children}</ThemedView>
      </ScrollView>
    </ThemedView>
  </SafeAreaView>
);

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  scrollView: {
    flexGrow: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
  },
});

export default ParallaxScrollView;
